In [1]:
import pandas as pd
import numpy as np
from IPython.display import display

In [2]:
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})
display(df1)

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [4]:
# --------------SHAPE---------------#

display(df1.shape) # its an attribute we dont use bracket while calling attributes

(5, 3)

In [9]:
#-----------------COLUMNS  AND ROW --> LABELS----------------#

display(df1.columns)
display(df1.index)

Index(['A', 'B', 'C'], dtype='object')

RangeIndex(start=0, stop=5, step=1)

In [10]:
#-------------------GENERAL INFORMATION------------#
display(df1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

None

In [13]:
#--------DESCRIBING DATA ( MIN MAX STD MEAN COUNT)--------------#

display(df1.describe())

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000