In [1]:
import numpy as np
import pandas as pd
from IPython.display import display

In [3]:

df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

display(df1 , df2)

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [5]:
#------------------CONCATINATION------------------#

display(pd.concat([df1,df2]))

display(pd.concat([df2,df1]))

# common columns are stacked........

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2